version: '3.8'
services:
    #nginx:
    #    image: nginx:stable-alpine
    #    container_name: nginx
    #    restart: always
    #    ports:
    #        - 8031:80
    #    volumes:
    #        - ./src:/var/www/html
    #        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #    depends_on:
    #        - php
    #        - mysql
    #    networks:
    #        - laravel
    
    mysql_db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            - MYSQL_DATABASE=apiMeli
            - MYSQL_UESR=root
            - MYSQL_PASSWORD=311034
            - MYSQL_ROOT_PASSWORD=311034
            - MYSQL_HOST=mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - laravel

    #php service
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        ports:
            - 8001:80
        networks:
            - laravel

networks:
    laravel:

